Add 'getSubscriptions' API on Server.
moquette-io/moquette pull request #212
Opened 2016-09-16 13:58 UTC by teranisi

Here is an implementation of [#207](https://github.com/andsel/moquette/issues/207) and related test.

2016-09-16 14:13 UTC, kevto commented on broker/src/test/java/io/moquette/server/ServerIntegrationEmbeddedPublishTest.java
> +    private void subscribeToWithQosAndNoCleanSession(String topic, int qos) throws Exception {
Unit test is not verifying any constraints or whatsoever.

2016-09-16 14:14 UTC, kevto commented on broker/src/test/java/io/moquette/server/ServerIntegrationEmbeddedPublishTest.java
> +    private void connectNoCleanSession() throws Exception {
Unit test is not verifying any constraints or whatsoever.

2016-09-16 14:16 UTC, kevto requested changes
Two notes regarding unit tests.

2016-09-16 14:19 UTC, kevto commented
Perhaps also an idea to make these `List` instances immutable? I don't know what your exact intentions are but if you're only looking for to read data and not mutate any of it, to make these objects immutable rather than allowing out of package classes to modify `Subscription` data.

2016-09-16 14:42 UTC, andsel commented
I agree with @kevto no mutable state has to be shared. I'll review the pr
when I'm back from holiday
Andre
Il giorno 16/set/2016 16:19, "Kevin" <notifications@github.com> ha scritto:

> Perhaps also an idea to make these List instances immutable? I don't know
> what your exact intentions are but if you're only looking for to read data
> and not mutate any of it, to make these objects immutable rather than
> allowing out of package classes to modify Subscription data.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/andsel/moquette/pull/212#issuecomment-247612583>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA_Y0UAlQrNGi7lwwUd8Mn78x87IhqU5ks5qqqVngaJpZM4J-94t>
> .
>

2016-09-17 05:49 UTC, teranisi commented
My intention was to provide a read interface for an external program. The objects can be immutable.

2016-10-26 11:46 UTC, merged