Fixed ServerLowLevel tests not running
moquette-io/moquette pull request #580
Opened 2021-02-18 12:19 UTC by hylkevds

JUnit only runs tests in classes that have a name that ends in Test,
the class in question had a name that ended in Tests, with an added s.
As a result, the tests in this class were never executed. This renames
the class to not have the added s.

2021-02-18 12:53 UTC, hylkevds commented
The first commit fixes the tests not running, the second commit adds a test for #573.
So the builds should all fail after the second commit, and be fixed again by PR #576.

2021-05-22 14:18 UTC, andsel requested changes
Hi @hylkevds the test is usefull, I would suggest some changes to be more explicit why some magic numbers are the values they are.

2021-05-22 14:18 UTC, andsel commented on broker/src/test/java/io/moquette/integration/ServerLowlevelMessagesIntegrationTest.java
> +                    TimeUnit.SECONDS.sleep(12);
12 seconds is more then 2 times of resend interval (https://github.com/moquette-io/moquette/blob/f6f3f6eedbb6b50128a25cb9c031662dd5ad043d/broker/src/main/java/io/moquette/broker/Session.java#L37) this direct linkage with this interval should be more explicit, so:
- move from `private` to `package private` or even `public` that constant and reuse here as `FLIGHT_BEFORE_RESEND_MS * 2`

2021-05-22 14:18 UTC, andsel commented on broker/src/test/java/io/moquette/integration/ServerLowlevelMessagesIntegrationTest.java
> +            CountDownLatch countDownLatch = new CountDownLatch(2);
The countdown latch initialized to 2 is redundant. It should be initialized to 1 and `countDown()` only when it reaches the second publish.

It could be done even more straightforward with Awaitility, for example:
```java
AtomicBoolean isFirst = new AtomicBoolean(true);
AtomicBoolean receivedPublish = new AtomicBoolean(false);
subscriber.subscribe(topic, 1, (String topic1, org.eclipse.paho.client.mqttv3.MqttMessage message) -> {
  if (isFirst.getAndSet(false)) {
    TimeUnit.MILLISECONDS.sleep(FLIGHT_BEFORE_RESEND_MS * 2);
  } else {
    receivedPublish.set(true); 
  }
});
publisher.publish(topic, "hello".getBytes(), 1, false);

Awaitility.await()
    .atMost(FLIGHT_BEFORE_RESEND_MS * 4, TimeUnit.MILLISECONDS)
    .pollInterval(FLIGHT_BEFORE_RESEND_MS, TimeUnit.MILLISECONDS)
    .untill(receivedPublish::get, equalTo(true));
   
```

2021-05-22 14:54 UTC, hylkevds commented on broker/src/test/java/io/moquette/integration/ServerLowlevelMessagesIntegrationTest.java
> +                    TimeUnit.SECONDS.sleep(12);
I agree using the constant is much nicer, but Session would also have to be made public for that to work...
Another option is to make a separate class for constants.
What would you prefer?

2021-05-22 15:08 UTC, andsel commented on broker/src/test/java/io/moquette/integration/ServerLowlevelMessagesIntegrationTest.java
> +            CountDownLatch countDownLatch = new CountDownLatch(2);
Is better is we move those two constants into `broker/src/main/java/io/moquette/BrokerConstants.java` wihtou changing visibility of `Session` class

2021-05-22 15:14 UTC, hylkevds commented on broker/src/test/java/io/moquette/integration/ServerLowlevelMessagesIntegrationTest.java
> +            CountDownLatch countDownLatch = new CountDownLatch(2);
Ok, I'll do that, and clean up the test.

2021-05-23 13:49 UTC, andsel approved these changes
LGTM

2021-05-23 13:51 UTC, merged