Fix #455, #587: qos2 cce and deadlock
moquette-io/moquette pull request #588
Opened 2021-02-25 14:56 UTC by hylkevds

This PR builds on top of #584

#455: resendInflightNotAcked() assumed all messages in the inflightWindow are
PublishedMessage, but they can also be PubRelMarker. This caused a
ClassCastException.

#587: When sending PubRelMessages, never put them on the queue, since this
deadlocks the system.

2021-07-03 08:22 UTC, andsel requested changes
Thank's @hylkevds please could you rebase this PR to `master` branch so that the becomes difference becomes more easy to spot and read. May thanks

2021-07-04 14:11 UTC, hylkevds commented
The force-push I did Friday was a rebase on the master branch.

2021-07-04 14:25 UTC, hylkevds commented
The change looks big, because it adds and removes an if statement. That makes the entire content of the if "change" even though it doesn't really change.

2021-07-09 14:06 UTC, andsel reviewed
Ive left a comment to describe why this generated a deadlock

2021-07-09 14:06 UTC, andsel commented on broker/src/main/java/io/moquette/broker/Session.java
> -        if (canSkipQueue()) {
@hylkevds could elaborate more on the reason why this if and the management of the slots created deadlock or any other problem?

2021-07-09 15:36 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/Session.java
> -        if (canSkipQueue()) {
(assuming I understand the inner workings correctly)

Lets say we have 10 inflight slots taken by QoS2 messages, and there are 1000 QoS2 messages in the queue waiting to be sent after a burst of activity.
We've just received a  message in the QoS2 workflow, so the workflow of this message is taking up a message slot.
If we give up our slot, we're not getting it back, since the messageQueue is not empty. canSkipQueue will return false.

The last step in one of our first 10 QoS2 workflows will now end up as message 1001 on the queue. We are going to try to start 1000 more QoS2 workflows before finishing the 10 we're already working on! But the client is most likely not going to respond to most of those 1000 new workflows, since the client also already has 10 workflows open (assuming the client also has 10 inflight slots).
So we're going to have to wait for all 1000 new workflows to time out before we get a free slot again to finish the first 10 workflows.

But:
The fact that we received this message means we have an inflight slot for this workflow.
The fact that we received this message also means we want to send a message and that the connection is open.
So why give up this slot, that we know we need for a message that the client really needs to close an open workflow? It's better to finish a workflow then to start a new one, so responses on messages in open workflows should have priority over messages that start new workflows and should thus not be put on the queue.

2021-07-09 16:05 UTC, andsel commented on broker/src/main/java/io/moquette/broker/Session.java
> -        if (canSkipQueue()) {
Thanks for explanation and good catch! I'll try to figure out hot to create a test for this case

2021-07-11 12:19 UTC, andsel commented on broker/src/main/java/io/moquette/broker/Session.java
> -        if (canSkipQueue()) {
This condition is difficult to test unit

2021-07-11 12:22 UTC, andsel approved these changes
LGTM

2021-07-11 12:23 UTC, merged