feat: expose netty enabled tls protocols option
moquette-io/moquette pull request #613
Opened 2021-07-22 15:37 UTC by jbutler

By exposing this configurations, customers can choose to disable older
or insecure versions of TLS. For example, with this change, it is
possible to force clients to use TLSv1.2

This was tested by using mosquitto client tools to force a specific TLS version and confirm that older protocols were, indeed, disabled. Though it would be nice to have an explicit test to this. I can look at adding one.

2022-05-21 17:17 UTC, jbutler commented
@andsel any thoughts on this? Our security team requires disabling older TLS versions, and I imaging this will be useful for others as well

2022-05-24 16:37 UTC, andsel requested changes
Thanks @jbutler to ping me, I lost it.
The idea seems good I would only add some parameter validation, since it's free text that the user has to type, and typos could happen.

2022-05-24 16:37 UTC, andsel commented on broker/src/main/java/io/moquette/broker/DefaultMoquetteSslContextCreator.java
> +                contextBuilder.protocols(enabledTLSProtocols.split(";"));
I think that since this parameter is passed down to Netty, we should perform some sort of parsing.
For example if the only admitted values are `TLSv1.2` and `TLSv1.3`, we could check the strings written by the user are effectively those two, and if's not warn the user with a log line.
The risk is to make Netty crashing with ugly exception.

2022-05-24 16:39 UTC, andsel commented on broker/src/main/java/io/moquette/broker/DefaultMoquetteSslContextCreator.java
> +                contextBuilder.protocols(enabledTLSProtocols.split(";"));
@jbutler do you think it's feasible to cover it with an integration test? 
I mean that once `TLSv1.2` is configured a client that tries to connect with `TLSv1.1` receives an error on connetion.

2022-05-25 17:20 UTC, jbutler commented on broker/src/main/java/io/moquette/broker/DefaultMoquetteSslContextCreator.java
> +                contextBuilder.protocols(enabledTLSProtocols.split(";"));
Absolutely. I can definitely make those changes. Thanks for taking a look

2022-06-07 04:48 UTC, jbutler commented
After doing a little bit of research on allowable TLS protocol strings, I've found that JDK8+ (at least sun and openjdk) disable older / insecure TLS protocols by default. Furthermore, this is also controllable directly via Java system properties.

So, this probably doesn't need to be exposed via Moquette config. I'll go ahead and close this PR for now.

2022-06-07 04:48 UTC, closed without merging

2022-06-07 07:04 UTC, andsel commented
Maybe I should add a section on the [guide](https://moquette-io.github.io/moquette/documentation.html) about this