Fix #629: Adding subscriptions is very slow
moquette-io/moquette pull request #630
Opened 2021-09-15 08:37 UTC by hylkevds

- Sort CNode.children by token
- made Token comparable
- made CNode.token final
- Changed all searches to use Collections.binarySearch()
- Changed inserts to respect sorting order

2023-05-29 10:19 UTC, hylkevds commented
This not only massively speeds up adding subscriptions, also matching publishes to subscriptions is much more efficient when there are many topics with subscriptions.

2023-06-17 14:48 UTC, andsel requested changes
I think the idea to switch to binarySearch is good, however, due to the facts that some optimizations are not easy to grasp, maybe each one could be separated in its own PS, describing well the optimization and why.

I would appreciate if the code could be accompanied with a test that with a huge set of sibling subscriptions shows the slowness. For example an insert or a search that fails after 5 minutes. 
In this way just switching the linear scan to binary search shows that time is reduced a lot.

2023-06-17 14:48 UTC, andsel commented on broker/src/test/java/io/moquette/integration/PublishToManySubscribersUseCaseTest.java
> -        int openSlotCount = COMMAND_QUEUE_SIZE;
I don't understand the reason why of this

2023-06-17 14:48 UTC, andsel commented on broker/src/main/java/io/moquette/broker/subscriptions/CNode.java
> +        int idx = Collections.binarySearch(children, token, (Object node, Object token1) -> ((INode) node).mainNode().token.compareTo((Token) token1));
All these `binarySearch` uses, forces casting, passing from Object, because the `token` is not of the right type.
It's better to pass through the compiler check to avoid runtime casting error at the price of creating a couple of instances, with something like:
```java
final INode tempTokenNode = new INode(new CNode(token));
        int idx = Collections.binarySearch(children, tempTokenNode, (INode node, INode tokenNode) -> node.mainNode().token.compareTo(tokenNode.mainNode().getToken()));
```

2023-06-17 14:48 UTC, andsel commented on broker/src/main/java/io/moquette/broker/subscriptions/CNode.java
> +            return null;
In previous code when `childOf` wasn't able to find an INode associated  to a Token it raised an IllegalArgumentException, I don't understand the reason to move to a null return.

2023-06-17 14:48 UTC, andsel commented on broker/src/main/java/io/moquette/broker/subscriptions/CNode.java
> +        int idx = Collections.binarySearch(children, newINode.mainNode().token, (Object node, Object token1) -> ((INode) node).mainNode().token.compareTo((Token) token1));
All instances of the binarySearch, maybe could be extracted in a helper method, to avoid code duplication.

2023-06-17 20:32 UTC, hylkevds commented
> I think the idea to switch to binarySearch is good, however, due to the facts that some optimizations are not easy to grasp, maybe each one could be separated in its own PS, describing well the optimization and why.

That's what the separate commits are for. Separating those into their own PRs makes no sense, since they don't work separately. Just go through the separate commits. You can even check them out individually with GIT to try them out locally.

> I would appreciate if the code could be accompanied with a test that with a huge set of sibling subscriptions shows the slowness. For example an insert or a search that fails after 5 minutes. In this way just switching the linear scan to binary search shows that time is reduced a lot.

That should be possible :)

2023-06-17 20:43 UTC, hylkevds commented on broker/src/test/java/io/moquette/integration/PublishToManySubscribersUseCaseTest.java
> -        int openSlotCount = COMMAND_QUEUE_SIZE;
Timing...
Because the code is now faster, it can flood the queue since each action generates more than one command on the Queue.
It used to work because the slowness of the insert delayed the creation of commands enough for the worker threads to catch up.

It surprised me too, but you should try it out for yourself :)

2023-06-17 21:40 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/subscriptions/CNode.java
> +            return null;
That's part of the "optimised away double lookup" commit. Often the code did a `anyChildrenMatch()` followed by a `childOf()` meaning it did the expensive lookup twice. That's really inefficient of course. So to remove this superfluous `anyChildrenMatch()` call, we make `childOf()` return null if there is no such child. We could do an `Optional`, but since it's not a public interface that seemed redundant.

2023-06-17 21:47 UTC, hylkevds commented
> I would appreciate if the code could be accompanied with a test that with a huge set of sibling subscriptions shows the slowness. For example an insert or a search that fails after 5 minutes.

I've added two tests that together run in ~4 seconds with the new code on my machine, but time out after 5 minutes with the old code.

2023-06-17 22:06 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/subscriptions/CNode.java
> +        int idx = Collections.binarySearch(children, token, (Object node, Object token1) -> ((INode) node).mainNode().token.compareTo((Token) token1));
Good point. I've created a method for the binarySearch and cleaned up the types.

2023-06-17 22:07 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/subscriptions/CNode.java
> +        int idx = Collections.binarySearch(children, newINode.mainNode().token, (Object node, Object token1) -> ((INode) node).mainNode().token.compareTo((Token) token1));
Good idea. Done :)

2023-06-19 14:48 UTC, andsel commented on broker/src/main/java/io/moquette/broker/subscriptions/CNode.java
> +            return null;
Going step by step is much easier and now I can see the motivation of the changes. Maybe a more descriptive comment for the "Optimised away all instances that loop over all children" case. Something like:
```
Not all next level children has to be verified recursively, but only the multi level any (#) the single level one (+) or the only matching node with the next head token part.
```

2023-06-19 15:01 UTC, andsel requested changes
Thank's @hylkevds  for your patience.  The PR is pretty good, just a couple of final touches.

2023-06-19 15:01 UTC, andsel commented on broker/src/main/java/io/moquette/broker/subscriptions/CNode.java
> +            return null;
I think would better to be more explicit. `null`is speedy but could drive us to the NPE. I think would be better to explicitly return an `Optional`, it's designed for cases such this.

2023-06-19 15:01 UTC, andsel commented on broker/src/test/java/io/moquette/broker/subscriptions/CTrieSpeedTest.java
> + * Copyright (c) 2012-2018 The original author or authors
```suggestion
 * Copyright (c) 2012-2023 The original author or authors
```

2023-06-19 15:01 UTC, andsel commented on broker/src/test/java/io/moquette/broker/subscriptions/CTrieSpeedTest.java
> +        }
```suggestion
        for (int v = 0; topicIdx < TOTAL_SUBSCRIPTIONS / 10; topicIdx++) {
            for (int clientIdx = 0; clientIdx < 10; clientIdx++) {
                count++;
                results.add(clientSubOnTopic("Client-" + clientIdx, "mainTopic-" + topicIdx));
            }
        }
```

Instead of `a` and `b`, using something more expressive would help readability

2023-06-19 15:01 UTC, andsel commented on broker/src/test/java/io/moquette/broker/subscriptions/CTrieSpeedTest.java
> +        }
```suggestion
        for (int clientIdx = 0; clientIdx < countPerLevel; clientIdx++) {
            for (int rootLayerIdx = 0; rootLayerIdx < countPerLevel; rootLayerIdx++) {
                for (int firstLayerIdx = 0; firstLayerIdx < countPerLevel; firstLayerIdx++) {
                    for (int secondLayerIdx = 0; secondLayerIdx < countPerLevel; secondLayerIdx++) {
                        count++;
                        results.add(clientSubOnTopic("Client-" + clientIdx, "mainTopic-" + rootLayerIdx + "/subTopic-" + firstLayerIdx + "/subSubTopic" + secondLayerIdx));
                        if (count >= TOTAL_SUBSCRIPTIONS) {
                            break outerloop;
                        }
                    }
                }
            }
        }
```

The same spirit could be applied here, with better naming could increase readability

2023-06-19 15:09 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/subscriptions/CNode.java
> +            return null;
Sure, I can update the commit message with a longer explanation.

2023-06-19 16:47 UTC, hylkevds commented on broker/src/test/java/io/moquette/broker/subscriptions/CTrieSpeedTest.java
> + * Copyright (c) 2012-2018 The original author or authors
Good point, I've updated it.

In FROST-Server we're now using spotless-maven-plugin to automatically check the licence header and code formatting. When something isn't how it should be it can also automatically apply the corrections.

2023-06-19 16:47 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/subscriptions/CNode.java
> +            return null;
No Problem, updated!

2023-06-19 16:54 UTC, hylkevds commented on broker/src/test/java/io/moquette/broker/subscriptions/CTrieSpeedTest.java
> +        }
Sure, no problem. Also for the other method.

2023-06-20 18:59 UTC, andsel approved these changes
Great work LGTM!

2023-06-20 19:04 UTC, merged