Feature/intro session events processors fixes
moquette-io/moquette pull request #637
Opened 2022-01-01 22:34 UTC by hylkevds

After quite a bit more testing I found some loose threads. Most I've fixed prototypically in a PR #:

* Disconnects must be handled on the sessionExecutors Threads, otherwise the session create logic breaks.
* Queues were never removed from QueueRepositories, not even in case of cleanSession.
* Queues in the Repositories were always reused, even in case of cleanSession.
* Queues were in some cases removed from the local queue cache, while in-use.
* Messages on queues and in Sessions were not released when discarded.
* Session.mqttConnection can be set to null with messages still in the queue.
* Processor threads were not stopped on server exit.

With the fixes in PR # memory use is quite constant, and Netty doesn't complain. The Unit Tests do cause Netty to complain about unreleased buffers, but I've not found the cause yet.

I'm not sure the failedPublishes collection is a good way to solve command queues being full. It moves the problem from a fixed size queue to a limitless queue. Especially since the only reason for a failure at this point is a full command queue, and putting the message in the FailedPublishCollection does not reduce the load (it actually increases load). Blocking until the command queue has space is probably more effective. We just have to make sure no messages are added to the command queues by the sessionExecutors Threads.

One last important ToDo is Persistent Sessions. They are never removed, gathering messages, even when the client never reconnects. We'll need to figure a way to add a configurable timeout for persistent sessions...

2022-01-03 16:26 UTC, andsel requested changes
Hi @hylkevds left some notes as discussed at https://github.com/moquette-io/moquette/issues/608#issuecomment-1004198215

2022-01-03 16:26 UTC, andsel commented on broker/src/main/java/io/moquette/broker/Session.java
> +        final MQTTConnection myMqttConnection = mqttConnection;
It's not clean why copy the field in local variable before the check.
Also it's not clear to me why it becomes null. The `null` assignment is done at  https://github.com/moquette-io/moquette/blob/1b1bac76fa9be9e9bb0b28be3fs c627afee684d73/broker/src/main/java/io/moquette/broker/Session.java#L181 during `disconnect` of the `Session`.  
So the NPE here could happen only if a client disconnected and the send PUB QoS2 which is a weird behavior that shouldn't happen because the DISCONNECT and the PUB are handled serially by the same thread.

2022-01-03 16:26 UTC, andsel commented on broker/src/main/java/io/moquette/broker/Session.java
> +        if (myMqttConnection != null && canSkipQueue()) {
Here the null check is correct because the PUB is processed by a different thread that could have executed the DISCONNECT.
I would avoid to name the local reference to the mqttConnection as `myMqttConnection`, something like `localMqttConnectionReference` or similar (have not better ideas).
The same for the `sendPublishQos2` method

2022-01-05 15:39 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/Session.java
> +        final MQTTConnection myMqttConnection = mqttConnection;
Indeed, I removed this instance of the check.

2022-01-05 15:40 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/Session.java
> +        if (myMqttConnection != null && canSkipQueue()) {
Ok, I've renamed the local variables.

2022-01-15 16:28 UTC, andsel reviewed
@hylkevds thanks for sahring this, I brought this commit to PR #631 with some little changes

2022-01-15 16:28 UTC, andsel commented on broker/src/main/java/io/moquette/broker/PostOffice.java
> +                publishFutures.add(routeCommand(subCommands[i].eventLoopNr, subCommands[i]));
I think that here there is the risk to send the bulk publish command to an unrelated session queue.

The target queueId is determined by 
```java
Math.abs(sub.getClientId().hashCode()) % this.eventLoops
```
but if we used that id, convert to string and route it again I don't thing that a second execution of the formula gives same result.

Support the `clientId` is `subscriber_0` the `targetQueueId` after first application of the modulo is `2`.
If we convert the integer to to the string `"2"` and re-apply the formula on it, we could have 1 as result.

So  it goes to be processed by the incorrect Session Event Loop.

2022-01-15 17:02 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/PostOffice.java
> +                publishFutures.add(routeCommand(subCommands[i].eventLoopNr, subCommands[i]));
Yeah, that's not quite correct yet. The reason for passing the targetQueue number is to make it easier to find out which of the queues was the one that caused a failure if one of the futures returned a failure.
Instead we should just pass the first clientId that we encountered for that targetQueue... Or add a routeComand that accepts a queueId instead of a clientId?

2022-01-16 11:14 UTC, andsel commented on broker/src/main/java/io/moquette/broker/PostOffice.java
> +                publishFutures.add(routeCommand(subCommands[i].eventLoopNr, subCommands[i]));
I used the first encountered clientId.
To identify which queue has the problem, given the clientId it's always possible to recalculate it.

2022-01-29 11:20 UTC, andsel commented
#631 has been merged, so I think this PR could be closed.

2022-01-29 19:06 UTC, hylkevds commented
This PR is no longer relevant.

2022-01-29 19:06 UTC, closed without merging