Fixed oquette broker kills parent application if embedded and broker port already used #641
moquette-io/moquette pull request #646
Opened 2022-02-01 15:47 UTC by sbaranov-iqmessenger

[#641](https://github.com/moquette-io/moquette/issues/641)
just there was removed System.exit(1)

2022-02-20 18:43 UTC, andsel commented
The `io.moquette.broker.Server` class is also used in `bat` and `sh` scripts used by the tar.gz distribution of Moquette. To complete this PR we should create another class (maybe `io.moquette.broker.Launcher` that simply wrap `Server` and catch for the exceptions, because in case of bind error, it should exit with error code without ugly traces in the console.

2022-02-22 08:26 UTC, sbaranov-iqmessenger commented
> The `io.moquette.broker.Server` class is also used in `bat` and `sh` scripts used by the tar.gz distribution of Moquette. To complete this PR we should create another class (maybe `io.moquette.broker.Launcher` that simply wrap `Server` and catch for the exceptions, because in case of bind error, it should exit with error code without ugly traces in the console.

I didn't change current exception "culture" and don't throw BindException to not add additional exceptions in method signatures. What do you think ?

2022-02-22 08:36 UTC, andsel requested changes
We are almost there, please integrate the suggestion and we are good to merge.

2022-02-22 08:36 UTC, andsel commented on broker/src/main/java/io/moquette/broker/NewNettyAcceptor.java
> +                throw new RuntimeException(ex);
```suggestion
               throw new RuntimeException("Cannot bind to port: " + port, ex);
```

2022-02-22 09:19 UTC, sbaranov-iqmessenger commented
> We are almost there, please integrate the suggestion and we are good to merge.

I've done what you suggested but is there any benefit of containing human readable "Cannot bind..." because in `Server.main` I don't log exception. I just call System.exit(1) without any logging

2022-02-22 09:24 UTC, andsel commented
> is there any benefit of containing human readable "Cannot bind..."

I think it's useful in the code that use that method, incorporating it as a library, maybe it want to log the cause of the error, if we don't throw a specific error excpetion.

2022-02-22 09:45 UTC, sbaranov-iqmessenger commented
> > is there any benefit of containing human readable "Cannot bind..."
> 
> I think it's useful in the code that use that method, incorporating it as a library, maybe it want to log the cause of the error, if we don't throw a specific error excpetion.

oh, yeah, you are right. I got it

2022-02-22 15:33 UTC, merged

2022-02-22 15:34 UTC, andsel commented
Thanks a lot @sbaranov-iqmessenger for contributing! Warm welcome