Fix 653 retained messages publishing
moquette-io/moquette pull request #658
Opened 2022-02-19 21:26 UTC by hylkevds

This PR adds a test for, and fixes #653.

Retained messages used a difference code-path that skipped the Session, and thus did not properly set up in-flight status. 
To fix this, this PR:
- Adds a test for retained messages at different QoS levels
- Makes the retained messages use the same code path as non-retained messages
- Removes the retained-specific code.
- Adds a `retained` flag to this code-path
- Adds a `retained` flag to `SessionRegistry.PublishedMessage` so the flag is stored for queued messages

2022-02-20 13:01 UTC, hylkevds commented
@andsel: Ready for review.
The build issue is fixed, on the build-server the initial retained publish was processed slow enough for the subscription to finish first, causing the initial publish to be sent to the subscriber, and not the retained message. The test is more robust now.

2022-02-20 18:10 UTC, andsel requested changes
Thank's @hylkevds for your work,
I've left some comments for changes, to try to minimize the code change, but more importantly to clean the intentions in some code paths.

2022-02-20 18:10 UTC, andsel commented on broker/src/main/java/io/moquette/broker/PostOffice.java
> +                targetSession.sendPublishOnSessionAtQos(retainedMsg.getTopic(), qos, payloadBuf, true);
Method like this was introduced to make explicit what it does, and avoid boolean flag that needed to investigate every time what that boolean flag was. So for example 
```java
targetSession.sendPublishOnSessionAtQos(retainedMsg.getTopic(), qos, payloadBuf, true);
``` 
becomes more explicit, specifying the intention with the method name itself
```java
targetSession.sendRetainedPublishOnSessionAtQos(retainedMsg.getTopic(), qos, payloadBuf);
``` 
 I wouldn't like remove, because the client code becomes more readable, and it's more clear its intention.
Every time we use a method with explicitly passed value of `true` or `false` to programatically pass the retained behavior, we could introduce a method with the `retained` suffix and the other with `notRetained`.

2022-02-20 18:10 UTC, andsel commented on broker/src/test/java/io/moquette/integration/ServerIntegrationRetainTest.java
> + * Copyright (c) 2012-2018 The original author or authors
```suggestion
 * Copyright (c) 2012-2022 The original author or authors
```

2022-02-20 18:10 UTC, andsel commented on broker/src/test/java/io/moquette/integration/ServerIntegrationRetainTest.java
> +    private static Server m_server;
I would avoid `m_` prefixed fields in new code base.

2022-02-20 18:10 UTC, andsel commented on broker/src/test/java/io/moquette/integration/ServerIntegrationRetainTest.java
> +        checkRetained(0, 0, false);
Using a parameter to make the check code customizable complicates the test code because needs conditionals.
Only for qos0 the messages could be not received, because it's a best effort. So we could create two methods that share some common logic:

```java
public void publishRetained(int qosPub, int qosSub) throws Exception {
        final String topic = "/topic" + qosPub + qosSub;
        final String messageString = "Hello world MQTT " + qosPub + " " + qosSub;
        clientPublisher.subscribe(topic);
        clientPublisher.publish(topic, messageString.getBytes(UTF_8), qosPub, true);
        // Wait for the publish to finish
        Awaitility.await().until(() -> callbackPublisher.isMessageReceived());
        callbackPublisher.getMessageImmediate();

        clientSubscriber.subscribe(topic, qosSub);
}

public void verifyShouldReceive(int qosPub, int qosSub) {
    final boolean messageReceived = callbackSubscriber.isMessageReceived();
    if (messageReceived) {
      verifyReceive(qosPub, qosSub);
    }
}

public void verifyMustReceive(int qosPub, int qosSub) {
    assertTrue(callbackSubscriber.isMessageReceived(), "Expected message to be received");
    verifyReceive(qosPub, qosSub);
}


public void verifyReceive(int qosPub, int qosSub) {
    MqttMessage message = callbackSubscriber.retrieveMessage();
    assertEquals(messageString, message.toString());
    assertEquals(Math.min(qosPub, qosSub), message.getQos());
}


@Test
public void checkSubscriberQoS0ReceiveQoS0Retained() throws Exception {
    publishRetained(0, 0);
    verifyShouldReceive(0, 0);
}    
...
@Test
public void checkSubscriberQoS0ReceiveQoS1Retained() throws Exception {
    publishRetained(1, 0);
    verifyReceive(1, 0);

}

```

2022-02-20 18:11 UTC, andsel commented
@hylkevds another quick note, these tests seems more suitable to be parameterized test: https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests

2022-02-20 18:56 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/PostOffice.java
> +                targetSession.sendPublishOnSessionAtQos(retainedMsg.getTopic(), qos, payloadBuf, true);
I could do:

```
    public void sendRetainedPublishOnSessionAtQos(Topic topic, MqttQoS qos, ByteBuf payload) {
        sendPublishOnSessionAtQos(topic, qos, payload, true);
    }

    public void sendNonRetainedPublishOnSessionAtQos(Topic topic, MqttQoS qos, ByteBuf payload) {
        sendPublishOnSessionAtQos(topic, qos, payload, true);
    }

    private void sendPublishOnSessionAtQos(Topic topic, MqttQoS qos, ByteBuf payload, boolean retained) { ... }
```

That still minimises code duplication.

2022-02-20 18:58 UTC, hylkevds commented on broker/src/test/java/io/moquette/integration/ServerIntegrationRetainTest.java
> +    private static Server m_server;
No problem.
What was the reason you used that prefix originally?

2022-02-20 19:02 UTC, hylkevds commented
> @hylkevds another quick note, these tests seems more suitable to be parameterized test: https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests

Yep, I copied the test from `ServerIntegrationQoSValidationTest`, we should convert that one too at some point.

2022-02-20 19:08 UTC, andsel commented
Was stolen from cpp practice, m stay for member, it dates when Moquette was
started and the same practice was used by Apache Felix, so I stool the
idea. But the time proven, it's useless, also the 'this.' with ide like
idea are just more text to read.

Il dom 20 feb 2022, 19:58 Hylke van der Schaaf ***@***.***>
ha scritto:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> broker/src/test/java/io/moquette/integration/ServerIntegrationRetainTest.java
> <https://github.com/moquette-io/moquette/pull/658#discussion_r810669265>:
>
> > +    private static IConfig m_config;
> +    private static Server m_server;
>
> No problem.
> What was the reason you used that prefix originally?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/moquette-io/moquette/pull/658#discussion_r810669265>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH5RUPHBVOXQRGYUEUYIBDU4E2U3ANCNFSM5O3PERJA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2022-02-20 19:11 UTC, hylkevds commented on broker/src/test/java/io/moquette/integration/ServerIntegrationRetainTest.java
> +        checkRetained(0, 0, false);
Actually, for QoS0 we currently do not retain at all, we only clean any previous retain:
https://github.com/moquette-io/moquette/blob/main/broker/src/main/java/io/moquette/broker/PostOffice.java#L314-L322
Do we want to change that? If so, probably better to do that in a separate Issue/PR...

2022-02-20 19:54 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/PostOffice.java
> +                targetSession.sendPublishOnSessionAtQos(retainedMsg.getTopic(), qos, payloadBuf, true);
Ok, updated in 10b6d637fe3ad09720fe560153231a3ef7b079e5

2022-02-20 20:42 UTC, hylkevds commented on broker/src/test/java/io/moquette/integration/ServerIntegrationRetainTest.java
> +        checkRetained(0, 0, false);
I've parameterised the test. That turns out quite nice!

Since the current broker does not retain QoS0 messages, I've kept the explicit checks for this, and made these methods:
```
private void validateMustReceive(int qosPub, int qosSub)
private void validateMustNotReceive(int qosPub)
```

I've also extended the test to test if the retain is cleaned up when sensing an empty retained message.

2022-02-25 08:26 UTC, andsel requested changes
Hi @hylkevds, left just a couple of notes about the naming (`not` vs `non`) plus I think there is an issue with tests that doesn't cover the retained flag to `true` while is should be to `false` .  However we are close to get it merged.

2022-02-25 08:26 UTC, andsel commented on broker/src/main/java/io/moquette/broker/MQTTConnection.java
> +    static MqttPublishMessage createNonRetainedPublishMessage(String topic, MqttQoS qos, ByteBuf message,
```suggestion
    static MqttPublishMessage createNotRetainedPublishMessage(String topic, MqttQoS qos, ByteBuf message,
```

2022-02-25 08:26 UTC, andsel commented on broker/src/main/java/io/moquette/broker/Session.java
> +            MqttPublishMessage publishMsg = MQTTConnection.createNonRetainedPublishMessage(topic.toString(), qos,
```suggestion
            MqttPublishMessage publishMsg = MQTTConnection.createNotRetainedPublishMessage(topic.toString(), qos,
```

2022-02-25 08:26 UTC, andsel commented on broker/src/main/java/io/moquette/broker/Session.java
> +            MqttPublishMessage publishMsg = MQTTConnection.createNonRetainedPublishMessage(topic.toString(), qos,
```suggestion
            MqttPublishMessage publishMsg = MQTTConnection.createNotRetainedPublishMessage(topic.toString(), qos,
```

2022-02-25 08:26 UTC, andsel commented on broker/src/main/java/io/moquette/broker/Session.java
> +            MqttPublishMessage publishMsg = MQTTConnection.createNonRetainedPublishMessage(
```suggestion
            MqttPublishMessage publishMsg = MQTTConnection.createNotRetainedPublishMessage(
```

2022-02-25 08:26 UTC, andsel commented on broker/src/main/java/io/moquette/broker/Session.java
> +    public void sendNonRetainedPublishOnSessionAtQos(Topic topic, MqttQoS qos, ByteBuf payload) {
```suggestion
    public void sendNotRetainedPublishOnSessionAtQos(Topic topic, MqttQoS qos, ByteBuf payload) {
```

2022-02-25 08:26 UTC, andsel commented on broker/src/test/java/io/moquette/broker/SessionTest.java
> +        client.sendNonRetainedPublishOnSessionAtQos(destinationTopic, MqttQoS.AT_LEAST_ONCE, payload);
```suggestion
        client.sendNotRetainedPublishOnSessionAtQos(destinationTopic, MqttQoS.AT_LEAST_ONCE, payload);
```

2022-02-25 08:26 UTC, andsel commented on broker/src/main/java/io/moquette/broker/Session.java
> +        sendPublishOnSessionAtQos(topic, qos, payload, true);
I'm little bit confused about this. The method name says "not retained" but the `retain` flag is passed to `true`.
If this didn't trigger any test error, would it mean that tests doesn't cover enough, for example checking the retain flag in published message the subscriber?
Please update the test to catch this and then switch the flag that prove the fix solved.

2022-02-25 08:42 UTC, hylkevds commented
> Hi @hylkevds, left just a couple of notes about the naming (`not` vs `non`) 

Is that a convention you use? Since nonretained is the proper English variant. the sentence

> send (a) not retained publish

is not correct English. While the sentence

> send (a) nonretained publish

is correct... Hence my automatic use of the "non" variant.

2022-02-25 08:51 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/Session.java
> +        sendPublishOnSessionAtQos(topic, qos, payload, true);
Ohh, good catch!
I'll extend the test to check that normal messages are not sent with a retained flag.

2022-02-25 09:06 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/Session.java
> +        sendPublishOnSessionAtQos(topic, qos, payload, true);
I also added a test to check if QoS0 retained messages cancel an existing retain.

2022-02-25 09:26 UTC, andsel commented
@hylkevds about https://github.com/moquette-io/moquette/pull/658#issuecomment-1050650027 my bad, keep the `non`

2022-02-25 09:34 UTC, andsel requested changes
Left a minor nitpick

2022-02-25 09:34 UTC, andsel commented on broker/src/test/java/io/moquette/integration/ServerIntegrationRetainTest.java
> +        Assertions.assertTrue(messageReceived, "Expected a message retained at QoS " + qosPub + ".");
Just a note on `Assertions.assertTrue` Assertions.assertFalse`, in all the other part of the code I used the static import of the assert method, for example `assertEquals`, we should keep the same convention.
Last step then we can marge.

2022-02-25 09:37 UTC, hylkevds commented on broker/src/test/java/io/moquette/integration/ServerIntegrationRetainTest.java
> +        Assertions.assertTrue(messageReceived, "Expected a message retained at QoS " + qosPub + ".");
> @hylkevds about [#658 (comment)](https://github.com/moquette-io/moquette/pull/658#issuecomment-1050650027) my bad, keep the `non`

For consistency, shall I also change all other occurrences of notRetained to nonRetained in code that did not change otherwise? Like the `PostOfficeInternalPublishTest` ?

2022-02-25 09:39 UTC, andsel commented on broker/src/test/java/io/moquette/integration/ServerIntegrationRetainTest.java
> +        Assertions.assertTrue(messageReceived, "Expected a message retained at QoS " + qosPub + ".");
Yes please, but do in another follow up PR

2022-02-25 09:45 UTC, hylkevds commented on broker/src/test/java/io/moquette/integration/ServerIntegrationRetainTest.java
> +        Assertions.assertTrue(messageReceived, "Expected a message retained at QoS " + qosPub + ".");
Ok, I'll use "not" in this PR, and create a new "spelling" PR to change all uses of notRetained to nonRetained

2022-02-25 10:40 UTC, merged