Moved session calls to the session-queue
moquette-io/moquette pull request #725
Opened 2023-02-13 16:20 UTC by hylkevds

There were some non-queue related threading issues that popped up during testing of the Unsafe Queues. Some Session actions were not put on the command queue.

2023-03-18 18:09 UTC, andsel requested changes
Left a comment on a possible mismatch.

2023-03-18 18:09 UTC, andsel commented on broker/src/main/java/io/moquette/broker/MQTTConnection.java
> +            queueDrainQueueCommand();
Why invoking asynchronously the `flushAllQueuedMessages` method instead of keeping the original `writabilityChanged` ?

2023-03-19 18:47 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/MQTTConnection.java
> +            queueDrainQueueCommand();
Indeed, that like should not have been in this commit.

2023-03-19 18:54 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/MQTTConnection.java
> +            queueDrainQueueCommand();
Ah, actually, it does the same.
It's a call to the session, so it must happen in the command loop. And since `bindedSession.writabilityChanged();` in turn only calls `drainQueueToConnection()` we can just use the same function to directly call that method through the command queue.

2023-03-20 09:29 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/MQTTConnection.java
> +            queueDrainQueueCommand();
I've changed it back to a direct call to `bindedSession.writabilityChanged()`, wrapped in a queue call.

2023-03-20 11:01 UTC, andsel approved these changes
LGTM

2023-03-20 11:05 UTC, merged