feat: peer cert as username
moquette-io/moquette pull request #775
Opened 2023-09-18 12:15 UTC by MikeDombo

Rebase of https://github.com/moquette-io/moquette/pull/675

This PR adds enables authenticating clients based on their peer certificates without changing the existing authentication interface. This functionality is enabled by the addition of a new configuration option which passes the client certificate PEM in place of `username`. The EMQx broker also has the same configuration option.

There is also a very small change to behavior with this PR. Previously, clients that did not provide a password were immediately rejected if anonymous sessions were disabled. As far as I can tell, the spec allows username without a password. The code will now allow this and pass the username and empty password to the authenticator.

Why is this needed?
The existing auth interfaces are insufficient when clients need to be identified based on their client certificate. The current interfaces only support username, password, and client ID without any ability for authenticators and authorizers to use the client certificate (if provided) for authN/authZ.

By passing in the client certificate as username, this allows the authorizer to uniquely identify clients and authenticate and authorize based on this cryptographically secure identity.

Close #675

2023-09-18 12:16 UTC, MikeDombo commented
@andsel rebased PR ready for your review. The peer cert behavior is behind a BrokerConfiguration flag which is disabled by default.

2023-09-28 14:33 UTC, andsel requested changes
The idea seems good, however I would add an integration test with a real client that uses TLS connection and the server that validates the client identity using the provided certificate.

2023-09-28 14:33 UTC, andsel commented on broker/src/main/java/io/moquette/broker/security/PemUtils.java
> + * Copyright (c) 2022 The original author or authors
```suggestion
 * Copyright (c) 2023 The original author or authors
```

2023-09-28 14:33 UTC, andsel commented on broker/src/main/java/io/moquette/broker/security/PemUtils.java
> +        /**
```suggestion

        /**
```

2023-09-28 14:33 UTC, andsel commented on broker/src/main/java/io/moquette/broker/security/PemUtils.java
> +        /**
```suggestion

        /**
```

2023-09-28 14:33 UTC, andsel commented on broker/src/main/java/io/moquette/broker/security/PemUtils.java
> +        }
```suggestion
        }
        
```

2023-09-28 14:33 UTC, andsel commented on broker/src/main/java/io/moquette/broker/security/PemUtils.java
> +        }
```suggestion
        }
        
```

2023-09-28 14:33 UTC, andsel commented on broker/src/main/java/io/moquette/broker/security/PemUtils.java
> +        }
```suggestion
        }
        
```

2023-09-28 14:33 UTC, andsel commented on broker/src/main/java/io/moquette/broker/security/PemUtils.java
> +             PemWriter pemWriter = new PemWriter(str)) {
```suggestion
        try (StringWriter str = new StringWriter();
               PemWriter pemWriter = new PemWriter(str)) {
```

2023-09-28 14:33 UTC, andsel commented on broker/src/main/java/io/moquette/broker/security/PemUtils.java
> +            pemWriter.close();
But `pemWriter` isn't closed automatically by the `try` statement?

2023-09-28 14:33 UTC, andsel commented on broker/src/main/java/io/moquette/broker/MQTTConnection.java
> +            }
This code could be extracted in a method named `readClientProvidedCertificates(channel)`

2023-09-28 14:36 UTC, andsel commented
> If the authorizer allows the operation, then a malicious client could exploit this to publish (or subscribe) to topics it should not normally be authorized on.

If the authorizer assumes that the operation is coming from the old client and denies the operation, then it is possible for operations which should be allowed to be be silently rejected (as Moquette does not disconnect clients after authZ failures).


Please could you describe better?
Then, do you think that if authz fails, Moquette should close the connection? I think this is a weakness in Moquette, so could be a separate issue (in case file one issue for that)

2023-09-28 14:39 UTC, MikeDombo commented on broker/src/main/java/io/moquette/broker/security/PemUtils.java
> +            pemWriter.close();
It is closed automatically yes, however it needs to be closed before calling `str.toString()` or else the `str` will not contain the correct contents due to the buffered nature of `BufferedWriter` which `PemWriter` extends.

2023-09-28 14:42 UTC, MikeDombo commented on broker/src/main/java/io/moquette/broker/MQTTConnection.java
> +            }
Updated.

2023-09-28 14:49 UTC, MikeDombo commented
Thank you for the review @andsel.

I've updated the simple parts for formatting and extracting method.

> I would add an integration test with a real client that uses TLS connection and the server that validates the client identity using the provided certificate.

Are there any existing integration tests that you can point to which use either TLS or better yet, mutual TLS with client certs?

As for the authorizer bit of the description, I took that from the previous PR and it is possible that it no longer applies due to the significant session changes from 0.15 to 0.17. The idea was that an implementor of `IAuthorizatorPolicy` only gets the client ID and no other identifying information, so if the authorizer is caching information based on the client ID, then a malicious client connecting with the same client ID would inherit the permissions from the trusted client.

I will update the description to simplify since this is really just about providing a nicer way to offer TLS mutual auth for devices with client certificates.

As a separate point to this PR, yes I do think that unauthorized actions should kick the client (at least as an option); this is what AWS IoT Core does.

2023-09-28 15:18 UTC, MikeDombo commented
Added more testing with real TLS.

2023-09-29 08:48 UTC, andsel requested changes
Thanks a lot @MikeDombo for this. I've a  concern about setup method, if you could separate would be great.
Add also a line in the Changelog please 🙏 

Thanks for the effort in sustaining the project.

2023-09-29 08:48 UTC, andsel commented on broker/src/test/java/io/moquette/integration/ServerIntegrationSSLClientAuthTest.java
> -    @BeforeEach
I wouldn't miss the automatic call of common fixture setup. Instead, given that the authenticate with certificate is a new test case, we could add a new TestCase class, that contains only the 2 new added tests and common code with this class could be exported in an Abstract class. But the `BeforeEach` setup method autocall is something that should be preserved.

2023-09-29 11:24 UTC, MikeDombo commented on broker/src/test/java/io/moquette/integration/ServerIntegrationSSLClientAuthTest.java
> -    @BeforeEach
Thank you for the reviews. Updated tests and extracted `ServerIntegrationSSLClientAuthBase` and put back the before each calls.

2023-09-29 12:02 UTC, andsel requested changes
We are really close, just one refactoring step and then the PR is perfect to be merged, I think.

2023-09-29 12:02 UTC, andsel commented on broker/src/test/java/io/moquette/integration/ServerIntegrationSSLClientAuthCertAsUsernameTest.java
> + * Copyright (c) 2012-2018 The original author or authors
```suggestion
 * Copyright (c) 2012-2023 The original author or authors
```

2023-09-29 12:02 UTC, andsel commented on broker/src/test/java/io/moquette/integration/ServerIntegrationSSLClientAuthCertAsUsernameTest.java
> +        sslProps.put(IConfig.PEER_CERTIFICATE_AS_USERNAME, "true");
These are almost the same set of properties defined in `ServerIntegrationSSLClientAuthTest` ([code ref](https://github.com/moquette-io/moquette/pull/775/files#diff-da4f6800f723568f557325a1e75c9cac9f684e9081a2f755ca4955be66d81376R62-R70)) so could be extracted in a method that prepare and return Properties instance in the abstract class.

2023-09-29 12:13 UTC, MikeDombo commented on broker/src/test/java/io/moquette/integration/ServerIntegrationSSLClientAuthCertAsUsernameTest.java
> +        sslProps.put(IConfig.PEER_CERTIFICATE_AS_USERNAME, "true");
Thank you, updated.

2023-09-29 12:17 UTC, andsel approved these changes
LGTM

2023-09-29 13:40 UTC, merged