internalPublish now can send to specific clientId
moquette-io/moquette pull request #786
Opened 2023-11-02 06:44 UTC by maxwang789

1.  internalPublish now can send to specific client 
2. add config to generate unique ClientID for each client

The original request is that one request will be sent to topic "/request", but the response should be sent back on another topic "/response".
With these modifications, the embedding broker could distinguish all connections. 

Correct me if I'm wrong.

2023-11-02 09:24 UTC, hylkevds commented
That seems to be a feature that inherently violates the MQTT spec. Every client that has a subscription to a given Topic must get every (QoS dependent) message sent to this Topic.

The MQTT 5 spec adds a request/response mechanism that explains how to send a message to a specific client, by negotiating a private Topic for this client.

2023-11-06 05:33 UTC, maxwang789 commented
> That seems to be a feature that inherently violates the MQTT spec. Every client that has a subscription to a given Topic must get every (QoS dependent) message sent to this Topic.
> 
> The MQTT 5 spec adds a request/response mechanism that explains how to send a message to a specific client, by negotiating a private Topic for this client.

Yes, MQTT v5 add new mechanism. But it needs publisher and subscriber support new fields and new behaviors.
Sometime old equipment just uses MQTT as transport layer, it won't upgrade to MQTTv5.


And this modification is intended to be used in embedded server only, it won't change mqtt protocol or other behavior outside broker.

2023-11-14 08:51 UTC, hylkevds requested changes
I've added some questions and change requests.

2023-11-14 08:51 UTC, hylkevds commented on broker/src/main/java/io/moquette/BrokerConstants.java
> +    public static final String UNIQUE_CLIENT_ID="unique_client_id";
Please use the same formatting as other code.
(Not just on this line)

2023-11-14 08:51 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/PostOffice.java
> +            if (Objects.isNull(filterTargetClients)||filterTargetClients.isEmpty()|| filterTargetClients.contains(sub.getClientId())) {
Why did you change this line?

2023-11-14 08:51 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/PostOffice.java
> +        return internalPublish(msg,Collections.emptySet());
This should use the `NO_FILTER` constant, not the `emptySet()`.

2023-11-14 08:51 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/Server.java
> +        return internalPublish(msg,new HashSet<>(Collections.singletonList(clientId)));
This changes the semantics of `clientId`.
> @param clientId the id of the sending integration.

In other words, `clientId` is the _sender_, not the _receiver_.

2023-11-14 08:51 UTC, hylkevds commented on broker/src/test/java/io/moquette/integration/ServerIntegrationPahoCanPublishOnReadBlockedTopicTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Don't use star imports.

2023-11-14 08:51 UTC, hylkevds commented on broker/src/test/java/io/moquette/integration/ServerIntegrationPahoCanPublishOnReadBlockedTopicTest.java
> +        m_server.internalPublish(message, new HashSet<>());
This line should not need to be changed.

2023-11-14 08:51 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/MQTTConnection.java
> +            if(brokerConfig.isUniqueClientId()){
What is the reason for this code? ClientIds in MQTT are already unique.

2023-11-24 08:03 UTC, maxwang789 commented on broker/src/main/java/io/moquette/BrokerConstants.java
> +    public static final String UNIQUE_CLIENT_ID="unique_client_id";
I will change it to FORCE_UNIQUE_CLIENT_ID_PROPERTY_NAME

2023-11-24 08:07 UTC, hylkevds commented on broker/src/main/java/io/moquette/BrokerConstants.java
> +    public static final String UNIQUE_CLIENT_ID="unique_client_id";
The comment was not about the name of the property, but about the fact that the spaces around the equals-sign (`=`) are missing.

The fact that the client id is already unique per MQTT spec is a separate issue. I don't think this property is needed.

2023-11-24 08:09 UTC, maxwang789 commented on broker/src/main/java/io/moquette/broker/MQTTConnection.java
> +            if(brokerConfig.isUniqueClientId()){
NO, according to my test result.
1. If the client id is empty, it will generate a new clientId with new UUID
2. If the client is not empty, it just accepts original clientId. It may cause duplicate clientIds.

2023-11-24 08:11 UTC, maxwang789 commented on broker/src/main/java/io/moquette/broker/PostOffice.java
> +            if (Objects.isNull(filterTargetClients)||filterTargetClients.isEmpty()|| filterTargetClients.contains(sub.getClientId())) {
In previous logic, the empty filter means no matched.
It will filter out all clients and do nothing.
I just change the logic, no filter means everyone, it will send to every client without any filter.

2023-11-24 08:18 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/PostOffice.java
> +            if (Objects.isNull(filterTargetClients)||filterTargetClients.isEmpty()|| filterTargetClients.contains(sub.getClientId())) {
The previous logic worked correctly, with simpler logic. If the goal is to send to everyone, pass the NO_FILTER constant. If the goal is to send to a specific list of clients, use a list.

There is no need to change this.

2023-11-24 08:21 UTC, maxwang789 commented on broker/src/main/java/io/moquette/broker/PostOffice.java
> +        return internalPublish(msg,Collections.emptySet());
OK, I will change to NO_FILTER.
But I thought NO_FILTER should be pointed to Collections.EmptySet also because the intent of the variable means empty set and it should not be modified. 
A normal HashSet may be changed by mistake and cause unexpected behavior.

2023-11-24 08:21 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/MQTTConnection.java
> +            if(brokerConfig.isUniqueClientId()){
Reconnecting with the same client id will cause the previous connection with the same client id to be disconnected. Client IDs are unique, as specified in the MQTT specification.
Your code makes it impossible for a client to reconnect with the same client id, and receive all the messages that were not delivered yet due to the lost connection. This is a key part of the MQTT specification.

2023-11-24 08:24 UTC, maxwang789 commented on broker/src/main/java/io/moquette/broker/Server.java
> +        return internalPublish(msg,new HashSet<>(Collections.singletonList(clientId)));
oh, I may misunderstand the meaning of clientId here because the original clientId was discarded.
Should I introduce a new method such as internalPublishTo ?

2023-11-24 08:28 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/PostOffice.java
> +        return internalPublish(msg,Collections.emptySet());
NO_FILTER has different semantics from `Collections.EmptySet`. That's why NO_FILTER is not set to `Collections.EmptySet`. (`Collections.EmptySet` itself is a constant, so that's a very bad candidate for using as a filter contant)

Passing an empty list will cause the message to be sent to no-one. Which is consistent with the semantics of the method call.

2023-11-27 06:33 UTC, closed without merging