Support long client id. Add Netty native transport support on MacOS.
moquette-io/moquette pull request #806
Opened 2024-01-08 07:46 UTC by jingyu

## Release notes

[rn:skip] 

## What does this PR do?

- Support long client id. 
- Add Netty native trsansport support on MacOS. Bundle all the native transport module by default.

## Why is it important/What is the impact to the user?

The maximum length of the MQTT client identifier is increased to 256 from the 23 characters limit that is imposed by V3.1. The platform services often require longer client IDs.

Additionally, to facilitate development on MacOS,  support for the Netty KQueue native transport was added.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have updated the Changelog if it's a feature or a fix that has to be reported

## Author's Checklist

- [ ]

## How to test this PR locally

- For the long client ID: All test cases under `io.moquette.integration.mqtt5` should run correctly.
- For KQueue transport: If you enable `netty.native` in the config file on MacOS, you should see the message "Netty is using KQueue" in the console output when starting the Moquette server.

## Related issues

- 

## Use cases

2024-01-08 12:47 UTC, MikeDombo commented
Longer client IDs are supported when you connect using MQTT v3.1.1 instead of v3.1 or v3. Make sure that your client is connecting with the proper protocol version

2024-01-09 03:17 UTC, jingyu commented
> Longer client IDs are supported when you connect using MQTT v3.1.1 instead of v3.1 or v3. Make sure that your client is connecting with the proper protocol version

Yes, both MQTT 3.1.1 and 5.0 can support long client IDs. Therefore, I have reverted the changes related to the clientId and retained only the KQueue support in this PR.

Thank you! @MikeDombo

2024-02-04 09:36 UTC, andsel requested changes
Adds a line to the Changelog file, then I think we are good to go

2024-02-04 09:36 UTC, andsel commented on broker/pom.xml
> +          <classifier>linux-x86_64</classifier>
```suggestion
          <groupId>io.netty</groupId>
          <artifactId>netty-transport-native-epoll</artifactId>
          <version>${netty.version}</version>
          <classifier>linux-x86_64</classifier>
```

Align all `version` xml tags, in this use and all the other newly introuced

2024-02-14 15:24 UTC, jingyu commented on broker/pom.xml
> +          <classifier>linux-x86_64</classifier>
Fixed the indent

2024-02-14 15:25 UTC, jingyu commented on broker/pom.xml
> +          <classifier>linux-x86_64</classifier>
also updated the change log

2024-03-22 15:22 UTC, andsel approved these changes
LGTM

2024-03-22 15:22 UTC, merged

2024-03-22 15:23 UTC, andsel commented
Thanks a lot @jingyu for contributing with this :-) PR merged

2024-03-26 01:13 UTC, jingyu commented
> Thanks a lot @jingyu for contributing with this :-) PR merged

My pleasure to contribute to Moquette project  :-)