Fixed SegmentedQueues not being cleaned up on session purge
moquette-io/moquette pull request #833
Opened 2024-04-29 14:37 UTC by hylkevds

Segmented queues were closed, but not cleared on session close. This resulted in segments not being returned to the pool, and thus disk-space not being released. The queues were also not removed from the QueuePool, resulting in a memory leak.

Relates #734

2024-05-24 14:01 UTC, andsel requested changes
Hi @hylkevds thanks for this PR. I would also add unit test on the `unsafequeues.Queue` or `unsafequeues.QueuePool` to verify that a queue purge or close give back the segments to be reused.

2024-05-24 14:01 UTC, andsel commented on broker/src/main/java/io/moquette/broker/SessionRegistry.java
> +            unsubscribe(old);
Are we sure that `pool`'s session is the same instance of current session?

2024-05-25 19:17 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/SessionRegistry.java
> +            unsubscribe(old);
The only situation where it could happen that there are two sessions with the same clientID is when a client re-connects with cleanSession=true. In that case the old session is purged before the new session is created.

I can change the code to only remove from the pool if the session is the same as the one in the pool.

That just lead me to a different potential issue, with the `sessionExpirationService` timer. I think that timer could trigger right as a client is reconnecting, and as it is based on the `clientID`, it could kill a session that was just made. Shouldn't `removeExpiredSession` check if the session really is expired, and not reconnected? And probably do the cleanup on the session thread?

2024-05-25 19:17 UTC, hylkevds commented
> Hi @hylkevds thanks for this PR. I would also add unit test on the `unsafequeues.Queue` or `unsafequeues.QueuePool` to verify that a queue purge or close give back the segments to be reused.

I'll look into making some tests for this.

2024-06-02 08:19 UTC, andsel commented on broker/src/main/java/io/moquette/broker/SessionRegistry.java
> +            unsubscribe(old);
> I think that timer could trigger right as a client is reconnecting, and as it is based on the clientID, it could kill a session that was just made. Shouldn't removeExpiredSession check if the session really is expired, and not reconnected? And probably do the cleanup on the session thread?

Why, when a session disconnect it's also untracked from the session expiration service. When it reconnects it's tracked again, reinserting the reference into the pool managed by the session expiration service.
In this way all session tracked by the expiration service are session present in the session registry, and so can't be the case of a duplication.

2024-06-02 18:24 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/SessionRegistry.java
> +            unsubscribe(old);
The session expiration service only contains _disconnected_ sessions that have _cleanSession=false_. Sessions that are connected don't need to be tracked since they can't expire, and sessions with cleanSession=true are cleaned up on disconnect.

Imagine a disconnected session with cleanSession=false. The expiration service finds it in the queue and removes it for cleaning, but there is a time interval between it being removed from the queue and it being actually cleaned. Either because there is a large batch of sessions to expire, or because the thread is put in hold. In that time the user reconnects, and a new session is made that inherits the subscriptions and clientID of the old session. Now the expiration thread is reactivated and kills the thread with the stored clientID...

2024-06-03 07:58 UTC, andsel commented on broker/src/main/java/io/moquette/broker/SessionRegistry.java
> +            unsubscribe(old);
@hylkevds you are right! Very good explanation of the case. I think this aspect should be kept out of this PR, and an issue tracking the problem should opened so be solved. Thanks for pointing it out 👍

2024-08-03 17:22 UTC, hylkevds commented
@andsel: I added a test to verify the queue cleanup and page-file re-use.

2024-08-17 14:54 UTC, andsel requested changes
Hi @hylkevds the changes are almost good, just a couple of nitpicks on the log messages, then the PR is done.

2024-08-17 14:54 UTC, andsel commented on broker/src/main/java/io/moquette/broker/unsafequeues/QueuePool.java
> +        segmentsAllocationLock.lock();
I would add a debug line here, like
```java
LOG.debug("Purging segments for queue {}", queueName);
```

2024-08-17 14:54 UTC, andsel commented on broker/src/main/java/io/moquette/broker/unsafequeues/QueuePool.java
> +                LOG.debug("Consumed tail segment {} from queue {}", segmentRef, queueName);
Would rewrite this log as

```suggestion
                LOG.debug("Purging segment {} from queue {}", segmentRef, queueName);
```

2024-08-18 13:55 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/unsafequeues/QueuePool.java
> +                LOG.debug("Consumed tail segment {} from queue {}", segmentRef, queueName);
No problem, I added both logging lines.

2025-07-26 14:01 UTC, andsel requested changes
Please keep this PR with only changes related to the persistent queues, that would help a lot the review and the change history of the project. 
Please create a follow up PR for the issue related to session management.

2025-07-26 14:01 UTC, andsel commented on broker/src/main/java/io/moquette/broker/SessionRegistry.java
> +    void remove(Session session) {
I would keep the fixes for session management out of this PR, so that's more clear what this PR does and simplify to understand the change history, reducing the scope of the PR

2025-07-27 19:06 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/SessionRegistry.java
> +    void remove(Session session) {
I've split the commit containing the SessionRegistry changes into a separate branch. PR coming soon...

2025-08-02 10:52 UTC, andsel approved these changes
LGTM

2025-08-02 10:53 UTC, merged

2025-08-02 10:53 UTC, andsel commented
Thanks @hylkevds for your contribution to the project!