Reduced memory use on Sessions by removing handled items from inflightTimeouts
moquette-io/moquette pull request #834
Opened 2024-04-29 14:41 UTC by hylkevds

Reduced memory use on busy Sessions by removing handled items from inflightTimeouts

Items in the inflightTimeouts DelayQueue were only ever removed when they timed out. But in normal operation the related messages would have been handled long before that. There should only ever be a number equal to the number of inflightSlots in the queue, but the queue would grow to the maximum number of messages ever handled in a 5 second interval. This made each session take much more memory than needed.

- Relates #734

2024-04-30 08:01 UTC, andsel requested changes
The idea is correct, just a nitpick to make it more expressive.

2024-04-30 08:01 UTC, andsel commented on broker/src/main/java/io/moquette/broker/Session.java
> +        inflightTimeouts.removeIf(d -> d.packetId == ackPacketId);
Please extract this on a method such as `cleanFromInflight`

```java
private void cleanFromInflight(int packetId) {
    inflightTimeouts.removeIf(d -> d.packetId == packetId);
}     
```

2024-04-30 08:31 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/Session.java
> +        inflightTimeouts.removeIf(d -> d.packetId == ackPacketId);
Wasn't sure which form you'd prefer, since it was only one line.
Commit Updated.

2024-05-01 09:34 UTC, andsel approved these changes
LGTM

2024-05-01 09:34 UTC, merged