Fixed ExpirationService not shutting down Executor
moquette-io/moquette pull request #835
Opened 2024-04-29 14:44 UTC by hylkevds

When shutting down the server the Executor Threads in ScheduledExpirationService instances were not terminated, resulting in a hanging server that would not shut down.

2024-04-30 07:53 UTC, andsel requested changes
The idea is correct, just a nit pick on the the visibility of the newly introduced field.

2024-04-30 07:53 UTC, andsel commented on broker/src/main/java/io/moquette/broker/scheduler/ScheduledExpirationService.java
> +    ScheduledExecutorService actionsExecutor;
Given that `actionsExecutor` is assigned only once in the constructor, this can be 

```suggestion
    private final ScheduledExecutorService actionsExecutor;
```

2024-04-30 08:35 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/scheduler/ScheduledExpirationService.java
> +    ScheduledExecutorService actionsExecutor;
Oops, fixed :)

2024-05-01 08:42 UTC, andsel approved these changes
LGTM

2024-05-01 08:43 UTC, merged

2024-05-01 08:43 UTC, andsel commented
Thank's @hylkevds for fixing it!