Optimised page file opening
moquette-io/moquette pull request #837
Opened 2024-04-30 08:27 UTC by hylkevds

Instead of mapping the entire page file every time a segment is re-used, we map the page file once, and re-use the mapped buffer for each segment.
The cache uses WeakReferences to ensure that a page file that is no longer used does not stay mapped.

2024-04-30 08:56 UTC, hylkevds commented
It seems the 200ms timeout on creating subscriptions is sometimes not enough on the GitHub CI environment:
https://github.com/moquette-io/moquette/blob/2092693c5d9d5bcb0468631416d064c3707ffa32/broker/src/test/java/io/moquette/testclient/Client.java#L211

Do you want me to create a PR to increase it to 300?

2024-05-24 13:55 UTC, andsel requested changes
The idea is good, I left a rename comment. 
Plus I would ask to add a line in changelog 🙏

2024-05-24 13:55 UTC, andsel commented on broker/src/main/java/io/moquette/broker/unsafequeues/PagedFilesAllocator.java
> +    private MappedByteBuffer getPageFile(int pageId) throws QueueException {
I would rename, get<something> is confusing, a getter with parameter. Better something more explicit, I would propose 
```suggestion
    private MappedByteBuffer openOrRetrievePageFile(int pageId) throws QueueException {
```

2024-05-25 18:29 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/unsafequeues/PagedFilesAllocator.java
> +    private MappedByteBuffer getPageFile(int pageId) throws QueueException {
Good point about not making getters with parameters, or getters that do more complicated stuff than just getting...
Fixed it!

2024-05-25 18:33 UTC, hylkevds commented on broker/src/main/java/io/moquette/broker/unsafequeues/PagedFilesAllocator.java
> +    private MappedByteBuffer getPageFile(int pageId) throws QueueException {
Also added the changelog entry.

2024-05-27 07:39 UTC, andsel approved these changes
LGTM

2024-05-27 07:40 UTC, merged

2024-05-27 07:40 UTC, andsel commented
Thank's @hylkevds for your contribution!